# Generated by Django 4.2.6 on 2023-10-22 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_img', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=3000, null=True)),
                ('networth', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='published', max_length=20)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('cover_img', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('trailer_id', models.CharField(blank=True, max_length=150, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_number', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.ManyToManyField(blank=True, related_name='episode_comments', to='streaming.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('premiere_date', models.DateField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('US', 'US'), ('North America', 'North America'), ('South America', 'South America'), ('Central America', 'Central America'), ('North East Africa', 'North East Africa'), ('Caribbean', 'Caribbean')], default='US', max_length=50)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('Show', 'Show')], default='Movie', max_length=6)),
                ('box_office', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('cover_img', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('trailer_id', models.CharField(blank=True, max_length=150, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cast', models.ManyToManyField(blank=True, to='streaming.actor')),
                ('comments', models.ManyToManyField(blank=True, related_name='movie_comments', to='streaming.comment')),
                ('genres', models.ManyToManyField(blank=True, to='streaming.genre')),
                ('language', models.ManyToManyField(blank=True, to='streaming.language')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('premiere_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('cover_img', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('trailer_id', models.CharField(blank=True, max_length=150, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowActorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.actor')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.show')),
            ],
            options={
                'unique_together': {('actor', 'show')},
            },
        ),
        migrations.AddField(
            model_name='show',
            name='cast',
            field=models.ManyToManyField(blank=True, through='streaming.ShowActorRole', to='streaming.actor'),
        ),
        migrations.AddField(
            model_name='show',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='show_comments', to='streaming.comment'),
        ),
        migrations.AddField(
            model_name='show',
            name='episodes',
            field=models.ManyToManyField(blank=True, related_name='season_episodes', to='streaming.episode'),
        ),
        migrations.AddField(
            model_name='show',
            name='genres',
            field=models.ManyToManyField(blank=True, to='streaming.genre'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('cover_img', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episodes', models.ManyToManyField(blank=True, related_name='season_set', to='streaming.episode')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.show')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail_pictures/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='streaming.movie')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_set', to='streaming.season'),
        ),
        migrations.AddField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.show'),
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, to='streaming.movie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='shows',
            field=models.ManyToManyField(blank=True, to='streaming.show'),
        ),
    ]
