# Generated by Django 4.2.6 on 2023-10-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_show_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC', 'NC'), ('TV', 'TV')], default='R', max_length=5),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='networth',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC', 'NC'), ('TV', 'TV')], default='R', max_length=5),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='region',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('CAM', 'CAM'), ('SD', 'SD'), ('HD', 'HD'), ('UHD', 'UHD')], default='HD', max_length=5),
        ),
        migrations.AlterField(
            model_name='movie',
            name='region',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('US', 'US'), ('Australia', 'Australia'), ('North America', 'North America'), ('South America', 'South America'), ('Central America', 'Central America'), ('North East Africa', 'North East Africa'), ('Caribbean', 'Caribbean')], default='US', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='show',
            name='country',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='language',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='quality',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC', 'NC'), ('TV', 'TV')], default='R', max_length=10),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
