# Generated by Django 4.2.6 on 2023-10-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_country_remove_show_country_remove_show_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
