# Generated by Django 4.2.6 on 2023-10-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_language_abbreviation_alter_language_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
