# Generated by Django 4.2.6 on 2023-10-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_alter_actor_name_alter_country_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('US', 'US'), ('Australia', 'Australia'), ('North America', 'North America'), ('South America', 'South America'), ('Central America', 'Central America'), ('North East Africa', 'North East Africa'), ('Caribbean', 'Caribbean')], default='North America', max_length=20),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='region',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('US', 'US'), ('Australia', 'Australia'), ('North America', 'North America'), ('South America', 'South America'), ('Central America', 'Central America'), ('North East Africa', 'North East Africa'), ('Caribbean', 'Caribbean')], default='North America', max_length=20),
        ),
    ]
