# Generated by Django 4.2.6 on 2023-10-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_rename_cover_img_episode_cover_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cover_img',
            new_name='cover_url',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='cover_img',
            new_name='cover_url',
        ),
        migrations.AddField(
            model_name='actor',
            name='profile_img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
