# Generated by Django 4.2.6 on 2023-10-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0013_remove_actor_country_actor_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
