# Generated by Django 4.2.6 on 2023-11-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0015_show_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
