# Generated by Django 4.2.6 on 2023-11-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0016_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='genre',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
